
default: all

# -Xlint:unchecked

all:
	javac wumpus/Room.java
	javac wumpus/Cave.java
	javac wumpus/Player.java
	javac wumpus/ClientHandler.java
	javac wumpus/Game.java
	javac wumpus/wumpServer.java
	
server:
	java wumpus.wumpServer

clean:
	rm wumpus/*.class
